cmake_minimum_required(VERSION 3.0.2)
project(warehouse_navigation)
set(CMAKE_CXX_STANDARD 17)
find_package(catkin REQUIRED COMPONENTS roscpp nav_msgs geometry_msgs std_msgs warehouse_costmap warehouse_interfaces)
catkin_package(CATKIN_DEPENDS roscpp warehouse_costmap warehouse_interfaces)
include_directories(${catkin_INCLUDE_DIRS})

add_executable(navigation_node src/navigation_node.cpp)
target_link_libraries(navigation_node ${catkin_LIBRARIES})
install(TARGETS navigation_node RUNTIME DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
