cmake_minimum_required(VERSION 3.0.2)
project(warehouse_interfaces)
set(CMAKE_CXX_STANDARD 17)
find_package(catkin REQUIRED COMPONENTS warehouse_costmap)
catkin_package(INCLUDE_DIRS include CATKIN_DEPENDS warehouse_costmap)
include_directories(include ${catkin_INCLUDE_DIRS})
install(DIRECTORY include/${PROJECT_NAME}/ DESTINATION ${CATKIN_PACKAGE_INCLUDE_DESTINATION})
